### ISSUE TITLE
Are test data the same as data used for adaptation?

### ISSUE THREAD

**Issue by dltkddn0525** [Albert0147/G-SFDA#11]
Hi. Thanks for sharing your research. 

I was wondering if the test data from target domain are the same as the data used for adaptation on the target domain. Because it seems your source code gives the same path to both dataset(https://github.com/Albert0147/G-SFDA/blob/main/train_tar_visda.py#L392-L395) . In my opinion, test data should not be accessed before evaluation even if they are unlabeled. Am I missing something, or is it an intended behavior?

Best regards.

**Comment by Albert0147** [comment]
Hi, it is. And this is the evaluation protocol of all mehtods in domain adaptation (as most benchmarks do not split target data into train and validation set), since they are unlabeled.

**Comment by dltkddn0525** [comment]
Thanks for fast reply!
