### ISSUE TITLE
About training office home dataset

### ISSUE THREAD

**Issue by mincheoree** [Albert0147/G-SFDA#3]
Thanks for your ingenious methods. I am really impressed by the methods 👍 
However, I'd like to ask few questions about while training. I first downloaded VIsDA dataset, but it seems like the dataset structure is a bit complicated, so I instead used office home dataset first. 
I am a little bit unsure that is it right to modify the Art, Clipart, ....txt files to fit my environment? 
Also, after downloading the resnet baseline model at the beginning after running the training command, it seems that there is no output for like an hour. May I ask how long it takes to train the office-home dataset? 
Thanks for reading this issue. I really appreciate it.

**Comment by Albert0147** [comment]
Hi, as mentioned in the readme, we use office-home.sh for training on Office-Home, insides it you can find the exact training command such as 
> python train_**src**_oh.py --dset p2c  --gpu_id 0 --home 

> python train_**tar**_oh.py --dset p2c  --gpu_id 0  --home

BTW, for VisDA, just use the following commands to download the dataset:
> cd ./data
> wget http://csr.bu.edu/ftp/visda17/clf/train.tar
> tar xvf train.tar

> wget http://csr.bu.edu/ftp/visda17/clf/validation.tar
> tar xvf validation.tar  

> wget http://csr.bu.edu/ftp/visda17/clf/test.tar
> tar xvf test.tar

> wget https://raw.githubusercontent.com/VisionLearningGroup/taskcv-2017-public/master/classification/data/image_list.txt

**Comment by mincheoree** [comment]
@Albert0147 
Oh I have downloaded the datasets via these. 
However, I found out that during training, I got error during passing of linear layer. 

```shell
Traceback (most recent call last):
  File "train_src_oh.py", line 232, in <module>
    train_source(args)
  File "train_src_oh.py", line 77, in train_source
    output0 = netC(outputs[0])
  File "/home/mchangaf/anaconda3/envs/sfda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mchangaf/G-SFDA/network.py", line 154, in forward
    x = self.fc(x)
  File "/home/mchangaf/anaconda3/envs/sfda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mchangaf/anaconda3/envs/sfda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/mchangaf/anaconda3/envs/sfda/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
4439 3551 888
0
torch.Size([64, 3, 224, 224])
```
The error message is following. Is it related to cuda and pytorch environment version compatibility? 
I ran sh file provided when I downloaded all the files.

**Comment by Albert0147** [comment]
I guess it is due to the cuda version. My environment is pytorch 1.3 with cuda 10.0. You can try running the code on cpu, if it works then the problem may be from the cuda version.

**Comment by mincheoree** [comment]
@Albert0147 Oh yes, I think it's the problem from the setting. 
BUT I downloaded all the packages from the requirements.txt provided in the repo. 
I tried with the cpu, but I got same error on fully connected layer. 
Can you give some directions on revision? 
Thanks for your time.

**Comment by Albert0147** [comment]
That is strange, I can run the code on my several different servers..

**Comment by mincheoree** [comment]
@Albert0147 
It was due to my Cuda hardware version issue. Thanks for the help!
