### ISSUE TITLE
Question about VisDA2017

### ISSUE THREAD

**Issue by miss-rain** [Albert0147/G-SFDA#5]
Good work!

we know VisDA2017 has three part: _train dataset, validation dataset, and test dataset._

In code (**train_src_visda.py and train_tar_visda.py**)

for training source model, G-SFDA use VisDA's _train dataset_ (90% train and 10% test)
for training target model, G-SFDA use VisDA's _validation dataset_ (shuffle =ture, batchSize)
for testing target model, G-SFDA  also use VisDA's _validation dataset_ (shuffle =false, batchSize*3)

one question: **why not use VisDA's test dataset?**

**Comment by Albert0147** [comment]
Hi, as the VisDA does not directly provide the label for its 'test' set, we do not use it, as all recent DA papers did.

**Comment by miss-rain** [comment]
Thanks for relpy.

another question: **why set batchSize*3 when testing target model?**

G-SFDA ues all and same  VisDA's validation dataset to train and test target model,  is it right?

**Comment by Albert0147** [comment]
Just to accelerate the evaluation, since you do not train this time.

**Comment by miss-rain** [comment]
Thanks but sorry,  i don't understand it

**Comment by Albert0147** [comment]
It does not matter, it will not influence the results. Small batch size means you need to load more times from the dataset to gpu memory and may slow the evaluation.

**Comment by miss-rain** [comment]
Ok got it.

G-SFDA use all and same VisDA's validation dataset to train and test target model, is it ok?

**Comment by Albert0147** [comment]
Yeah, just as all DA methods do.

**Comment by miss-rain** [comment]
When training source model , 
G-SFDA use 90% VisDA's train dataset  for traing ,and use 10% VisDA's train dataset  for testing.

while when training target model,
G-SFDA use 100% VisDA's validation dataset  for traing ,and use  same 100% VisDA's validation dataset  for testing.

Did i understand right?

**Comment by Albert0147** [comment]
yeah

**Comment by miss-rain** [comment]
Nice.

in code train_src_visda.py, lines 252.

When training source model ,
**Why G-SFDA use 100% VisDA's validation dataset for testing source model?**

**Comment by Albert0147** [comment]
just test on target domain...

**Comment by miss-rain** [comment]
That's mean test  init target model?

**Comment by Albert0147** [comment]
yep
